-- MySQL Script generated by MySQL Workbench
-- Wed Jul 12 08:49:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tp5
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tp5` ;

-- -----------------------------------------------------
-- Schema tp5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tp5` DEFAULT CHARACTER SET utf8 ;
USE `tp5` ;

-- -----------------------------------------------------
-- Table `tp5`.`medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tp5`.`medico` ;

CREATE TABLE IF NOT EXISTS `tp5`.`medico` (
  `Matricula` INT(11) NOT NULL,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `apellido` VARCHAR(30) NULL DEFAULT NULL,
  `especialidad` VARCHAR(20) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tp5`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tp5`.`paciente` ;

CREATE TABLE IF NOT EXISTS `tp5`.`paciente` (
  `nss` INT(11) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `domicilio` VARCHAR(50) NULL DEFAULT NULL,
  `codigo_postal` SMALLINT(6) NULL DEFAULT NULL,
  `telefono` VARCHAR(16) NULL DEFAULT NULL,
  `nro_historial_clinico` INT(11) NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`nro_historial_clinico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tp5`.`ingreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tp5`.`ingreso` ;

CREATE TABLE IF NOT EXISTS `tp5`.`ingreso` (
  `idingreso` INT(11) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `nro_habitacion` SMALLINT(6) NULL DEFAULT NULL,
  `nro_cama` SMALLINT(6) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `ingresocol` VARCHAR(45) NULL DEFAULT NULL,
  `matricula_medico` INT(11) NOT NULL,
  `nro_historial_paciente` INT(11) NOT NULL,
  PRIMARY KEY (`idingreso`),
  INDEX `fk_matricula_medico` (`matricula_medico` ASC) VISIBLE,
  INDEX `fk_nro_historial_paciente` (`nro_historial_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_medico`
    FOREIGN KEY (`matricula_medico`)
    REFERENCES `tp5`.`medico` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nro_historial_paciente`
    FOREIGN KEY (`nro_historial_paciente`)
    REFERENCES `tp5`.`paciente` (`nro_historial_clinico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
